### ISSUE TITLE
Docker compose outdated

### ISSUE THREAD

**Issue by tstorek** [crate/crate-howtos#168]
###  Documentation feedback
 
- Page title: Run CrateDB on Docker
- Page URL: https://crate.io/docs/crate/howtos/en/latest/deployment/containers/docker.rst
- Source: https://github.com/crate/crate-howtos/blob/master/docs/deployment/containers/docker.html

---

Hello, 

the docker compose file is outdated. Due to changes in elasticsearch and in docket-ce the nodes will not discover eachother anymore. Hence, the networking needs to be reconfigured. Please see here: https://github.com/deviantony/docker-elk/issues/455 

It took me quite a while until I found this. 

Additinally:

- Container_name is not supported in stack deployment. 
- explaination of the effect of servicename, hostname, and node.name(in args) would be very helpful. 
- I think you need to set node.name now, which is really a pain since the command args do not allow variable substitution in stack files

Especially when planing on a sophististicated reusable stack file for multiple deployments. 

It took me so long to figure out. I know that there is no support for docker-swarm but you even advertise it on the website. 

Cheers

**Comment by tstorek** [comment]
A better example would be maybe this one here. I mean it would be even nicer if also the node discovery would work via the proxy but this one should already work.

`
version: '3.7'
services:
  yourService:
    image: <service-image>
    hostname: <hostname>
    networks:
      - backend
    ports:
      - "xxxx:xxxx"
    deploy:
      replicas: 5
    environment:
      - CRATE_HOST=cratedb-proxy
      - CRATE_PORT=4202

  # We are accessing the cratedb via a proxy using roundrobin as basic loadbalancing mechanism.
  # In used proxy service (https://proxy.dockerflow.com/) is based on HA-Proxy and will 
  # reconfigure automatically when scaling the database on multiple nodes.
  cratedb-swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:latest
    hostname: crate-swarm-listener
    networks:
      - backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://cratedb-proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://cratedb-proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s            
      placement:           
        constraints: [node.role == manager]

  cratedb-proxy:
    image: dockerflow/docker-flow-proxy:latest
    hostname: cratedb-proxy
    ports: 
      - "4202:4202"  
    networks:
      - backend
    environment:
      - SERVICE_NAME=cratedb-proxy     
      - LISTENER_ADDRESS=cratedb-swarm-listener
      - MODE=swarm
      - BIND_PORTS=4202
    deploy:
      replicas: 2 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: 
          - node.labels.country==${COUNTRY:-DE}
            #- node.role==manager
            #- node.labels.type==storage
      update_config:
        parallelism: 1
        delay: 10s
     
  # Setup for cratedb as distributed time-series storage.
  # We use a three node setup here. All of them a eligable as master node.
  # In order to avoid a split brain scenario we want all of them up before selecting a master.
  # Only two nodes (cratedb01 and cratedb02) hold data which we place on our storage nodes via the docker labels.
  # An additional Master-Node (cratedb03) is always placed on one of the manager nodes of the swarm.
  # It only acts as coordinator and does not hold any persistant data and therefore free to move around.
  #
  # Please check release notes!
  # https://crate.io/docs/crate/guide/en/latest/deployment/containers/docker.html
  # Since Crate-DB uses the elastic stack under the hood for discovery we recommend to check:
  # https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html
  cratedb01:
    image: crate:${CRATE_VERSION:-4.1.5}
    hostname: "{{.Node.Hostname}}"
    networks:
      - backend
    # ports:
    #- "4203:4200"
    #- "4300:4300"
    #- "5432:5432"
    volumes:
      - /storage/cratedb:/data   
    # -Ccluster.name                 https://crate.io/docs/crate/reference/en/latest/config/node.html#basics
    # -Cnode.name                    https://crate.io/docs/crate/reference/en/latest/config/node.html#basics
    # -Cnetwork.host                 https://crate.io/docs/crate/reference/en/latest/config/node.html#hosts
    # -Cdiscovery.seed_hosts         https://crate.io/docs/crate/reference/en/latest/config/cluster.html#discovery
    # -Ccluster.initial_master_nodes https://crate.io/docs/crate/reference/en/latest/config/cluster.html#discovery
    # -Cauth.host_based.enabled      https://crate.io/docs/crate/reference/en/latest/config/node.html#host-based-authentication
    # -Chttp.cors.enabled            https://crate.io/docs/crate/reference/en/latest/config/node.html#cross-origin-resource-sharing-cors
    # -Chttp.cors.allow-origin       https://crate.io/docs/crate/reference/en/latest/config/node.html#cross-origin-resource-sharing-cors
    # -Cgateway.expected_nodes       https://crate.io/docs/crate/reference/en/latest/config/cluster.html#metadata-gateway
    # -Cgateway.recover_after_nodes  https://crate.io/docs/crate/reference/en/latest/config/cluster.html#metadata-gateway
    volumes:
      - /storage/cratedb:/data
    command: ["crate",
               "-Ccluster.name=<yourCluster>",
               "-Cnode.name=$$(hostname)",
               "-Cnode.data=true",
               "-Cnetwork.host=0.0.0.0",
               "-Cnetwork.publish_host=_eth0_",
               "-Cdiscovery.seed_hosts=cratedb02,cratedb03",
               "-Cauth.host_based.enabled=false",
               "-Ccluster.initial_master_nodes=coordinator,<hostname1>,<hostname2>",
               "-Chttp.cors.enabled=true",
               "-Chttp.cors.allow-origin='*'",
               "-Cgateway.expected_nodes=${EXPECTED_NODES:-3}",
               "-Cgateway.recover_after_nodes=${RECOVER_AFTER_NODES:-2}"] 
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.country==${COUNTRY:-DE}
          - node.hostname==n5geh-storage1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/,/cratedb01/
        - com.df.port.1=4200
        - com.df.srcPort.1=4202
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      disable: false
    # Limiting of logging
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 50m
    environment:
       - CRATE_HEAP_SIZE=2g
       - MAX_MAP_COUNT=262144
       - ES_JAVA_OPTS="-Xms1g -Xmx1g"
  
  cratedb02:
    image: crate:${CRATE_VERSION:-4.1.5}
    hostname: "{{.Node.Hostname}}"
    networks:
      - backend
    #  ports:
    #- "4204:4200"
    #- "4300:4300"
    #- "5432:5432"
    volumes:
      - /storage/cratedb:/data
    command: ["crate",
               "-Ccluster.name=<yourCluster>",
               "-Cnode.name=$$(hostname)",
               "-Cnode.data=true",
               "-Cnetwork.host=0.0.0.0",
               "-Cnetwork.publish_host=_eth0_",
               "-Cdiscovery.seed_hosts=cratedb01,cratedb03",
               "-Cauth.host_based.enabled=false",
               "-Ccluster.initial_master_nodes=coordinator,<hostname1>,<hostname2>",
               "-Chttp.cors.enabled=true",
               "-Chttp.cors.allow-origin='*'",
               "-Cgateway.expected_nodes=${EXPECTED_NODES:-3}",
               "-Cgateway.recover_after_nodes=${RECOVER_AFTER_NODES:-2}"]  
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.country==${COUNTRY:-DE}
          - node.hostname==n5geh-storage2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/,/cratedb02/
        - com.df.port.1=4200
        - com.df.srcPort.1=4202
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      disable: false
    # Limiting of logging
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 50m
    environment:
       - CRATE_HEAP_SIZE=2g
       - MAX_MAP_COUNT=262144
       - ES_JAVA_OPTS="-Xms1g -Xmx1g"
  
  cratedb03:
    image: crate:${CRATE_VERSION:-4.1.5}
    hostname: "{{.Node.Hostname}}"
    networks:
      - backend      
    # ports:
    #- "4205:4200"
    #- "4300:4300"
    #- "5432:5432"
    command: ["crate",
               "-Ccluster.name=<yourCluster>",
               "-Cnode.data=false",
               "-Cnode.name=coordinator",
               "-Cnetwork.host=0.0.0.0",
               "-Cnetwork.publish_host=_eth0_",
               "-Cdiscovery.seed_hosts=cratedb01,cratedb02",
               "-Cauth.host_based.enabled=false",
               "-Ccluster.initial_master_nodes=coordinator,<hostname1>,<hostname2>",
               "-Chttp.cors.enabled=true",
               "-Chttp.cors.allow-origin='*'",
               "-Cgateway.expected_nodes=${EXPECTED_NODES:-3}",
               "-Cgateway.recover_after_nodes=${RECOVER_AFTER_NODES:-2}"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.country==${COUNTRY:-DE}
          - node.role==manager
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/,/cratedb03/
        - com.df.port.1=4200
        - com.df.srcPort.1=4202
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      disable: false
    # Limiting of logging
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 50m
    environment:
       - CRATE_HEAP_SIZE=2g
       - MAX_MAP_COUNT=262144
       - ES_JAVA_OPTS="-Xms1g -Xmx1g"
         
networks:   
  backend:
    driver: overlay

`

**Comment by infoverload** [comment]
@tstorek Thank you for leaving such a detailed and useful feedback.  We appreciate it and will open up a PR to address the issue.

**Comment by tstorek** [comment]
Hi,
Please also have a look at tgis stack file:

https://github.com/N5GEH/n5geh.platform/blob/master/timeseries/docker-stack.yaml.HA.EXAMPLE

I wrote it for a setup only having two data nodes.

**Comment by mechanomi** [comment]
reopening as work is ongoing

**Comment by infoverload** [comment]
Hey @tstorek, I've updated the page here (https://crate.io/docs/crate/howtos/en/latest/deployment/containers/docker.html) and would love your feedback on the Docker Compose file.  I looked through your example and tried to work out a minimal setup that can allow one to get a CrateDB cluster up and running.  I tried to add configurations that are absolutely necessary and removed things that are already defaults in the latest version of Docker Compose.  

I am also curious to know how you are using CrateDB! :)

**Comment by tstorek** [comment]
Hi, 
I did not try you compose in detail, but as far as I remember, I definitely needed these lines: 
               "-Cnetwork.host=0.0.0.0",
               "-Cnetwork.publish_host=_eth0_",
Was there another change in docker-swarm lately or are you talking about the overlay network in docker in your description? The networks above need to be configured for elastic search. That's at least how I understand it. Thanks!

FYI: Since you ask :) We are using CrateDB research-related as time series storage in combination with FIWARE as an OSS for IoT systems in the energy domain:)

**Comment by infoverload** [comment]
@tstorek You are right! The `network.host` should be specified so that it doesn't automatically bind to the loopback address.  
According to the documentation, `network.host` sets both the `network.bind_host` and the `network.publish_host`: https://crate.io/docs/crate/reference/en/4.2/config/node.html#network-host

I learned that the latest version of Docker Compose (v3) will create a default bridge network driver if you don't specify anything.  But I suppose an overlay network might be more practical (since many users might be using multiple hosts).  It might be a good idea to make that more clear in the docs.  

Your research project sounds really interesting! How does it work with FIWARE exactly? How did you hear about CrateDB and what has been your experience so far with it? We are always interested in how people use our product and how we can improve. :)
