### ISSUE TITLE
Getting started with CrateDB Cloud

### ISSUE THREAD

**Issue by marregui** [crate/crate-howtos#177]
A step by step guide whereby we end up having a 3 node cluster on which we can run the ISS series tutorial if we choose to.

This request comes from a discussion.

**Comment by mechanomi** [comment]
@marregui thanks for reporting this issue! do you think it would make more sense to move this over to https://github.com/crate/cloud-howtos?

**Comment by marregui** [comment]
c'est fait! https://github.com/crate/cloud-howtos/issues/31
