### ISSUE TITLE
migrating-from-mongodb.rst appears to be out-of-date

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-howtos#198]
###  Documentation feedback

 
- Page title: Migrating from MongoDB
- Page URL: https://crate.io/docs/crate/howtos/en/latest/best-practices/migrating-from-mongodb.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/best-practices/migrating-from-mongodb.rst

---

this page appears to be out-of-date

**Comment by infoverload** [comment]
I would be interested in working on this.

**Comment by mechanomi** [comment]
@joemoe left this comment earlier: https://github.com/crate/tech-writing-domain/issues/15#issuecomment-661243279

looks like we can close this
