### ISSUE TITLE
insert with unnest drops invalid rows but documentation doesn't mention this in the how-to guide

### ISSUE THREAD

**Issue by kamejosh** [crate/crate-howtos#203]
###  Documentation feedback

 
- Page title: Insert methods
- Page URL: https://crate.io/docs/crate/howtos/en/latest/performance/inserts/methods.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/performance/inserts/methods.rst

---

Inserts done with `unnest` are one of crates recommended ways of handling big inserts. If only looking at this entry the biggest drawback of `unnest` is not mentioned and can be unexpected.

When doing insert with unnest, rows that produces errors when inserted will be dropped and there is no error indicating that an error happened see python example at the end. This is documented here:
https://crate.io/docs/crate/reference/en/4.1/sql/statements/insert.html?highlight=unnest#insert-from-dynamic-queries-constraints

I would expect that this is also mentioned (or linked) in the how-to guides.

```
conn = client.connect('localhost:4200')
cursor = conn.cursor()

cursor.execute("CREATE TABLE IF NOT EXISTS untest (payload OBJECT(DYNAMIC));")

stmt = "INSERT INTO untest (payload) (SELECT col1 FROM UNNEST(?));"
payload = [
    {"info": "this is a valid object"},
    {"": "this is a invalid object"},
    {"info": "this is another valid object"}
]

try:
    cursor.execute(stmt, (payload,))
except Exception as e:
    print(f"encountered exception: {e}")
```

using `cursor.rowcount` one could implement error handling themself but as this is not mentioned in the how-to guide i wouldn't expect it to be necessary.

**Comment by mechanomi** [comment]
thank you for the excellent suggestion, @kamejosh!
