### ISSUE TITLE
Missing Ubuntu 20 (focal) packages

### ISSUE THREAD

**Issue by proddata** [crate/crate-howtos#214]
###  Documentation feedback

 
- Page title: Run CrateDB on Ubuntu
- Page URL: https://crate.io/docs/crate/howtos/en/latest/deployment/linux/ubuntu.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/deployment/linux/ubuntu.rst

---

Documentation says that packages for focal are available, however they aren't.

see also https://community.crate.io/t/crate-on-ubuntu-focal-fossa-20-04/449

**Comment by mechanomi** [comment]
this has been resolved (focal is now available)
