### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by proddata** [crate/crate-howtos#237]
###  Documentation feedback

 
- Page title: Rolling upgrade
- Page URL: https://crate.io/docs/crate/howtos/en/latest/admin/rolling-upgrade.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/admin/rolling-upgrade.rst

---

Links are broken:
checked `Release Notes` and `Versions`... => 404

**Comment by mechanomi** [comment]
these appear to be working again. closing. please reopen if you can reproduce
