### ISSUE TITLE
Command in dockerentrypoint.sh maybe deprecated...

### ISSUE THREAD

**Issue by mrgodlive** [crate/crate-howtos#243]
###  Documentation feedback

 
- Page title: Run CrateDB on Kubernetes
- Page URL: https://crate.io/docs/crate/howtos/en/latest/deployment/containers/kubernetes.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/deployment/containers/kubernetes.rst

---

The command `- -Cdiscovery.zen.hosts_provider=srv` is deprecated as described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-settings.html
It also may cause a CrashLoopBackOff failure when trying to run the deployment in a three nodes kubernetes cluster.

**Comment by infoverload** [comment]
@mrgodlive Thanks for reporting this! We will take a look. :)

**Comment by mechanomi** [comment]
I have asked one of our core engineers to review this and get back to the @crate/tech-writing team

**Comment by autophagy** [comment]
@mrgodlive Thank you for flagging this up - you are correct, the ``discovery.zen.hosts_provider`` was removed in 4.0 (the tutorial uses a 3.x release). I will update the tutorial to be in sync with the latest cratedb stable release.

For reference, instead the following options should be passed for 4.0+ (assuming your crate nodes are named `crate-0, `crate-1`, etc):
```
-Ccluster.initial_master_nodes=crate-0,crate-1,crate-2
-Cdiscovery.seed_providers=srv
-Cdiscovery.srv.query=_crate-internal._tcp.crate-internal-service.${NAMESPACE}. svc.cluster.local
```
