### ISSUE TITLE
How-To Guides Menu is broken

### ISSUE THREAD

**Issue by proddata** [crate/crate-howtos#271]
###  Documentation feedback

 
- Page title: CrateDB How-To Guides
- Page URL: https://crate.io/docs/crate/howtos/en/latest/index.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/index.rst

---

How-To Guides menu doesn't unfold on the left side
![image](https://user-images.githubusercontent.com/23557193/110835486-26f60380-829f-11eb-87a7-fd6da235732e.png)

**Comment by matthijskrul** [comment]
The same goes for the CrateDB Cloud Howtos, oddly enough (and only that one). I have been inquiring about this, and have tried fixing it with a ToC update, but no luck so far :(

**Comment by proddata** [comment]
apparently this is being worked on

closed by https://github.com/crate/crate-docs-theme/pull/244

**Comment by amotl** [comment]
@matthijskrul just reported that this appears to still not be working, so I am kindly reopening the issue.

**Comment by noviro** [comment]
this is fixed now: https://crate-cloud-howtos.readthedocs.io/en/latest/
