### ISSUE TITLE
Upsert operation on KafkaConnect Sink in CrateDB

### ISSUE THREAD

**Issue by prakashru** [crate/crate-howtos#289]
###  Documentation feedback

 
- Page title: Data Ingestion using Kafka and Kafka Connect
- Page URL: https://crate.io/docs/crate/howtos/en/latest/integrations/kafka-connect.html
- Source: https://github.com/crate/crate-howtos/blob/master/docs/integrations/kafka-connect.rst

---

I am trying to use KafkaConnect Sink operation using Upsert operation. My Connector Sink command is below
```sql
CREATE SINK CONNECTOR SINK_TO_CRATE_02_6 WITH (
    'connection.backoff.ms'                   = 10000,
    'connector.class'                         = 'io.confluent.connect.jdbc.JdbcSinkConnector',
    'connection.url'                          = 'jdbc:postgresql://10.42.0.84:5432/guestbook?user=crate',
    'topics'                                  = 'tbl-student',
    'connection.password'		      = 'somePassword',
    'tasks.max'				      = 1, 
    'insert.mode'                             = 'upsert',
    'batch.size'			      = 5,
    'delete.enable'			      = 'true',
    'auto.evolve'			      = 'true',
    'pk.mode'				      = 'record_key',
    'pk.fields'				      = 'message_key',
    'table.name.format'			      = 'student'
);
```
Found that upsert is not working. Insert operation is working fine. 
What is the issue in above KafkaConnect Sink command? Pleas help

**Comment by mkleen** [comment]
Hello, 

the KafkaConnect Sink should work with Upsert operations. Could you maybe provide any additional information such as the schema of your table, the structure and the Avro schema of the entity and logs/errors from the KafkaConnect Sink ?

Thanks,

Michael
